### ISSUE TITLE
About the Document 

### ISSUE THREAD

**Issue by yaolei** [grizzlypeaksoftware/beginningcryptodevelopment#2]
Your  website:  https://www.grizzlypeaksoftware.com/articles?id=5vWBWo4Zpi02FSVCmQunxk
1.Is the Migrations.sol file is auto generate ？
2. Is there any information how to connect solidity work and DApp (I'm new hand and work on the front end, Maybe i'm not understand what's the relevance solidity and DApp)

BTW: The document is very clear and easy for understand. Thank you it's a big help for lean Web3

**Comment by grizzlypeaksoftware** [comment]
Thank you for the feedback about the documentation.  When you run the truffle.init command, the migrations folder and file automatically generate. 

I want to spend some time writing the next articles on how to create dApps as well.  But basically once a solidity contract is deployed to a blockchain, you can use web3.js,  a javascript library to interface with the contract from JavaScript

Check this doc out
https://web3js.readthedocs.io/en/v1.2.11/getting-started.html

Thanks again for reading my content!
